### ISSUE TITLE
Moto g power - pathnotfoundexception

### ISSUE THREAD

**Issue by Meowwmixx** [bsutton/handyman#12]
Soon as the app opens I get an error attaching a picture.
![Screenshot_20240729-062109](https://github.com/user-attachments/assets/af146b7f-cb07-4d0b-a19d-75dc80d7cfec)

**Comment by bsutton** [comment]
I found the problem.  A bug in the local db provide resulted in the backup not happening.

I'm pushing an update to the app store. 
I would guess the update should be available in the next 8 hours.

The version will report as 0.0.8 under the System | About menu - assuming you can get that far :)

**Comment by bsutton** [comment]
0.0.8 is now available from the google play store.
